package rosalind

import org.scalatest.FunSuite
import scala.collection.mutable.Stack
 
class DNATestSuite extends FunSuite {
 
  test("counting nucleotides with data from problem") {
    val counts = DNA.countNucleotides("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC")
    
    assert(counts('A') === 20)
    assert(counts('C') === 12)
    assert(counts('G') === 17)
    assert(counts('T') === 21)
  }

  test("counting nucleotides with real data") {
    val counts = DNA.countNucleotides(
"GTGGGGTCTACCCCAGTTACTTTCTGTATAGGTGAGGAGGCTGATTAAAAATTCTTCGTTTGTCTACTCCGATTGGCGAACACCATCCGATTGACAATGGTACTTATCCGAAGTGGATAAGCTCATACCCTATCGGAAAAGACCAAGTACCGACCCTCTACATATGAAGATGCTGTTTCAACGAATACGGTAGTTCCGCGACCAATCGATCATGTTCAAGGACTGTGCCAACCGACGGGTGGTGACCTAGCTGGACGTCCGGGAATTGGTTATCCTTACTATGGGGTAAGTCAGAGCCCATGTGTGGGAACAATTCTCTACCGACTGGGCTGCAAGTGGTGTAGCCCAGCTGTCCCCAGGGTACTTCGATGGTAGCGTGCCCGGCGCCCGTCAGGTCACTCACCCAGTTATTTTATGTTCGCCCAAGACAACCAAAGCAAAGCTATGTATCCCGCAGAAATTGGCTTACGAACTTACGTTTCTAAGGCCCTCATATGATTCTCGCCTGACCTTTACGACGGCGCAACCTGTCACGGTCCTACGAGCTCATTAGTCAGTATGCCATCCCCGTTTGGCATAGTTCGACGAAAAGTCCCTCCACCAGGCACATAAAATGTATTTGTTGCAGTACCTCCCACTGCGGTCCTAAAACTCGGAATTGGAATTTAGCCTGACACCAATAAGAAGTGGGCACTACTCCATTTTTTGAAGTGGTGGGGTCTTTTGGGTGGAATGGGCTGACGTGAGCTCAAACGCGACGATGTGTGCCTTCGCAGTAACTTCCCTCCAGAGAGTTACGGTATTACGGAATGTTA")
    
    assert(counts('A') === 199)
    assert(counts('C') === 205)
    assert(counts('G') === 199)
    assert(counts('T') === 212)
  }

}