package rosalind

import org.scalatest.FunSuite
import scala.collection.mutable.Stack
 
class DNATestSuite extends FunSuite {
 
  test("counting nucleotides with data from problem") {
    val counts = DNA.countNucleotides("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC")
    
    expect(20) { counts('A') }
    expect(12) { counts('C') }
    expect(17) { counts('G') }
    expect(21) { counts('T') }
  }

  test("counting nucleotides with real data") {
    val counts = DNA.countNucleotides(
"GTGGGGTCTACCCCAGTTACTTTCTGTATAGGTGAGGAGGCTGATTAAAAATTCTTCGTTTGTCTACTCCGATTGGCGAACACCATCCGATTGACAATGGTACTTATCCGAAGTGGATAAGCTCATACCCTATCGGAAAAGACCAAGTACCGACCCTCTACATATGAAGATGCTGTTTCAACGAATACGGTAGTTCCGCGACCAATCGATCATGTTCAAGGACTGTGCCAACCGACGGGTGGTGACCTAGCTGGACGTCCGGGAATTGGTTATCCTTACTATGGGGTAAGTCAGAGCCCATGTGTGGGAACAATTCTCTACCGACTGGGCTGCAAGTGGTGTAGCCCAGCTGTCCCCAGGGTACTTCGATGGTAGCGTGCCCGGCGCCCGTCAGGTCACTCACCCAGTTATTTTATGTTCGCCCAAGACAACCAAAGCAAAGCTATGTATCCCGCAGAAATTGGCTTACGAACTTACGTTTCTAAGGCCCTCATATGATTCTCGCCTGACCTTTACGACGGCGCAACCTGTCACGGTCCTACGAGCTCATTAGTCAGTATGCCATCCCCGTTTGGCATAGTTCGACGAAAAGTCCCTCCACCAGGCACATAAAATGTATTTGTTGCAGTACCTCCCACTGCGGTCCTAAAACTCGGAATTGGAATTTAGCCTGACACCAATAAGAAGTGGGCACTACTCCATTTTTTGAAGTGGTGGGGTCTTTTGGGTGGAATGGGCTGACGTGAGCTCAAACGCGACGATGTGTGCCTTCGCAGTAACTTCCCTCCAGAGAGTTACGGTATTACGGAATGTTA")
    
    expect(199) { counts('A') }
    expect(205) { counts('C') }
    expect(199) { counts('G') }
    expect(212) { counts('T') }
  }

}